import type { Metadata } from "next";
import "../../app/globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import Container from "@/components/container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <div className="min-h-screen bg-gray-100">
        <Container className="pt-0">{children}</Container>
      </div>

      <Toaster position="top-right" />
    </AuthProvider>
  );
}
