import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import Container from "@/components/container";
import Header from "@/components/header";
import ProtectedRoute from "@/components/ProtectedRoute";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter}  antialiased`}>
        <AuthProvider>
          <ProtectedRoute>
            <div className="min-h-screen bg-gray-100">
              <Header />
              <Container className="pt-0">{children}</Container>
            </div>
          </ProtectedRoute>

          <Toaster position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
